global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s

scrape_configs:

  # Prometheus self-monitoring

  - job_name: prometheus
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090

  # PHP metrics

  - job_name: php-metrics
    metrics_path: /metrics.php
    scheme: http
    static_configs:
      - targets:
          - nginx:80

  # cAdvisor metrics

  - job_name: cadvisor-metrics
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - cadvisor:8080
